FROM golang:1.22.4-alpine AS builder
WORKDIR /src
COPY . .
RUN go build -o /httpserver ./cmd/httpserver/server.go

FROM scratch AS final
WORKDIR /app
COPY --from=builder /httpserver /app
ENTRYPOINT [ "./httpserver" ]
