FROM golang:1.22.4-alpine AS builder
WORKDIR /src
COPY . .
RUN go build -o /ginserver ./cmd/ginserver/server.go

FROM scratch AS final
WORKDIR /app
COPY --from=builder /ginserver /app
ENTRYPOINT [ "./ginserver" ]





