name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      

    steps:
      - name: make install
        run: sudo apt install make -y
      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make test
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Format
        run: make fmt
      - name: Golangci Linter
        uses: golangci/golangci-lint-action@v6